### ISSUE TITLE
How to send Payload data

### ISSUE THREAD

**Issue by darmie** [Endare/node-bb10#12]
Hi, Thanks for this module... I would like to know how to send payload data with it using  a JSON format?

**Comment by SamVerschueren** [comment]
Hi, just send it as string with `JSON.stringify` and parse it client side with `JSON.parse`.

**Comment by darmie** [comment]
You mean like this? `var message = new pushLibrary.PushMessage(messageID, JSON.stringify({data:''}));`   

I am curious to know how the notification title will be displayed when it shows in the device.

**Comment by SamVerschueren** [comment]
Yes indeed, maybe the stringify isn't necessary server side. Long time ago I used this library.

You choose the notification title yourself on the client side when handling the push notification. So that has nothing to do with the payload being sent.

**Comment by darmie** [comment]
Ok. I mean if the app is closed... How does the notification display the title... or it doesn't at all?

Sorry I don't own a blackberry device.

**Comment by SamVerschueren** [comment]
No problem.

So the payload is received by the device and is forwarded to the application. The application should be set to `launchApplicationOnPush` which will open the app when a push notification is received. The client should retrieve the payload and create a notification manually (title, message, icon, ...). If the app is opened by a push message, it's up to the developer to close the app again after the notification is shown in the hub.

An example for cordova (webworks) can be found here: https://github.com/SamVerschueren/cordova-ua-bb10/blob/master/www/UAirship.js

**Comment by darmie** [comment]
Thank you Sam. My problem is solved.

**Comment by darmie** [comment]
Hi @SamVerschueren  I seem to have a problem with getting user's BB PIN. Please do you know how I could do this using webworks?

**Comment by SamVerschueren** [comment]
Please open a new issue next time.

It's an Urban Airship plugin but should get you going. https://github.com/SamVerschueren/cordova-ua-bb10

**Comment by darmie** [comment]
Sorry I didn't want to create a new issue over something that might turn out to be non-issue. :) 

I have walked through the UA plugin but I didn't see how to fetch BBM Pin. I am trying to avoid using the UA plugin as my client would not be willing to pay for yet another service like Urban Airship. That was why we decided to use our own push server.

**Comment by SamVerschueren** [comment]
Yes but it's the same principle. Instead of subscribing the user's device (PIN) with UA, it should subscribe the PIN with your service. That's why I said "it should get you going". 

[This](https://github.com/SamVerschueren/cordova-ua-bb10/blob/master/www/UAirship.js#L217) is the line you need, please look into the code first. With a few adjustments it should be fairly easy to let it call your own service.

**Comment by darmie** [comment]
I am sorry, I am not still clear. On the server side your API `message.addAllRecipients(['000000', '000000']);` . It requires the PIN of the users to add recipient.  I want to be able to send the user's PIN to the server so that when we want to send a message to a particular user.

**Comment by SamVerschueren** [comment]
The token that is retrieved by that line I referred to is the PIN of the user's device. It should be implemented in your app and your app should sent that token to your server.

**Comment by darmie** [comment]
Ok thank you, I had no idea that the token is the same as the PIN. Thanks!!
